[2024-06-25T13:06:17.350+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T13:06:17.446+0300] {taskinstance.py:2066} INFO - Dependencies not met for <TaskInstance: Ingest_Data.wait_for_fetch_task manual__2024-06-25T10:00:54.981160+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-06-25T10:06:17.445964+00:00 and task will be retried at 2024-06-25T10:11:13.694828+00:00.
[2024-06-25T13:06:17.458+0300] {local_task_job_runner.py:163} INFO - Task is not able to be run
[2024-06-25T13:26:35.587+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T13:26:35.689+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ingest_Data.wait_for_fetch_task manual__2024-06-25T10:00:54.981160+00:00 [queued]>
[2024-06-25T13:26:35.694+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ingest_Data.wait_for_fetch_task manual__2024-06-25T10:00:54.981160+00:00 [queued]>
[2024-06-25T13:26:35.694+0300] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-25T13:26:35.716+0300] {taskinstance.py:2330} INFO - Executing <Task(ExternalTaskSensor): wait_for_fetch_task> on 2024-06-25 10:00:54.981160+00:00
[2024-06-25T13:26:35.736+0300] {standard_task_runner.py:63} INFO - Started process 19999 to run task
[2024-06-25T13:26:35.743+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Ingest_Data', 'wait_for_fetch_task', 'manual__2024-06-25T10:00:54.981160+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/ingest_DAG.py', '--cfg-path', '/tmp/tmpp7jg4q24']
[2024-06-25T13:26:35.746+0300] {standard_task_runner.py:91} INFO - Job 19: Subtask wait_for_fetch_task
[2024-06-25T13:26:35.793+0300] {task_command.py:426} INFO - Running <TaskInstance: Ingest_Data.wait_for_fetch_task manual__2024-06-25T10:00:54.981160+00:00 [running]> on host DESKTOP-1R67MDQ.
[2024-06-25T13:26:35.850+0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Ingest_Data' AIRFLOW_CTX_TASK_ID='wait_for_fetch_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T10:00:54.981160+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-25T10:00:54.981160+00:00'
[2024-06-25T13:26:35.851+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T13:26:35.863+0300] {baseoperator.py:399} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2024-06-25T13:26:35.864+0300] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag fetch on 2024-06-25T10:00:54.981160+00:00 ... 
[2024-06-25T13:26:35.867+0300] {logging_mixin.py:188} WARNING - /home/user/rubix/internship_project/.venv/lib/python3.10/site-packages/airflow/utils/session.py:79 DeprecationWarning: This method is deprecated and will be removed in future.
[2024-06-25T13:27:35.871+0300] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag fetch on 2024-06-25T10:00:54.981160+00:00 ... 
[2024-06-25T13:28:35.879+0300] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag fetch on 2024-06-25T10:00:54.981160+00:00 ... 
[2024-06-25T13:29:35.890+0300] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag fetch on 2024-06-25T10:00:54.981160+00:00 ... 
[2024-06-25T13:30:35.901+0300] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag fetch on 2024-06-25T10:00:54.981160+00:00 ... 
[2024-06-25T13:31:35.913+0300] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag fetch on 2024-06-25T10:00:54.981160+00:00 ... 
[2024-06-25T13:32:35.918+0300] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag fetch on 2024-06-25T10:00:54.981160+00:00 ... 
[2024-06-25T13:33:35.922+0300] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag fetch on 2024-06-25T10:00:54.981160+00:00 ... 
[2024-06-25T13:34:35.932+0300] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag fetch on 2024-06-25T10:00:54.981160+00:00 ... 
[2024-06-25T13:34:40.550+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-25T13:34:40.555+0300] {process_utils.py:132} INFO - Sending Signals.SIGTERM to group 19999. PIDs of all processes in the group: [19999]
[2024-06-25T13:34:40.555+0300] {process_utils.py:87} INFO - Sending the signal Signals.SIGTERM to group 19999
[2024-06-25T13:34:40.556+0300] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-25T13:34:40.556+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T13:34:40.562+0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/user/rubix/internship_project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/user/rubix/internship_project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/user/rubix/internship_project/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/rubix/internship_project/.venv/lib/python3.10/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/user/rubix/internship_project/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/rubix/internship_project/.venv/lib/python3.10/site-packages/airflow/sensors/base.py", line 292, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/user/rubix/internship_project/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-06-25T13:34:40.566+0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Ingest_Data, task_id=wait_for_fetch_task, run_id=manual__2024-06-25T10:00:54.981160+00:00, execution_date=20240625T100054, start_date=20240625T102635, end_date=20240625T103440
[2024-06-25T13:34:40.612+0300] {process_utils.py:80} INFO - Process psutil.Process(pid=19999, status='terminated', exitcode=2, started='13:26:35') (19999) terminated with exit code 2
